### ISSUE TITLE
[ Control Panel ] - Add Check in Time Range Input to detect if invalid range

### ISSUE THREAD

**Issue by JayWebz** [CAIDA/ioda-ui#119]

**Comment by digizeph** [comment]
Clicking range, select `Today` and apply, then range seems to be wrong after that, and all graphs turn blank.

**Comment by JayWebz** [comment]
Resolved with https://github.com/CAIDA/ioda-ui/pull/131

**Comment by digizeph** [comment]
> Clicking range, select `Today` and apply, then range seems to be wrong after that, and all graphs turn blank.

The time range sets to `23:00:00` instead of `00:00:00` for some reason after clicking today.

**Comment by JayWebz** [comment]
Resolved with https://github.com/CAIDA/ioda-ui/pull/138 now.
