### ISSUE TITLE
[ Table ] - Add visual aid to convey which/how many data sources have a score on Summary Table

### ISSUE THREAD

**Issue by JayWebz** [CAIDA/ioda-ui#195]
It would be good to be able to see how many datasources are experiencing a score in the summary table. Column with checkboxes, tiny columns. It’s important to see which datasources are experiencing outages as well as the quantity. Datasource information should be currently available in the summary table api call.

**Comment by albertodainotti** [comment]
Note we would like it to happen without active user input

**Comment by JayWebz** [comment]
Alberto Notes - 
- Try it without the white framing
- use a more subtle gray color close to the background for the squares that are not colored

**Comment by JayWebz** [comment]
Updated with https://github.com/CAIDA/ioda-ui/pull/236
