### ISSUE TITLE
[ Global ] - Loading a large timespan of data crashes the website

### ISSUE THREAD

**Issue by JayWebz** [CAIDA/ioda-ui#199]
When loading 5 months of data, an error for maximum “RangeError: Maximum call stack size exceeded” happens in Chrome and Safari.

Example - https://dev.v2.ioda.caida.org/country/MM?from=1609459200&until=1620345599

**Comment by digizeph** [comment]
Adding `&maxPoints=3000` to limit the number of points returned to the graph would likely help with this.
Example: 
https://api.ioda.caida.org/dev/signals/raw/country/MM?from=1609459200&until=1620345599&maxPoints=3000

**Comment by JayWebz** [comment]
When calling a year's worth of data, there is a console error of maximum callback size exceeded. This is most likely due to calling so much granular data to populate the xy plot time series with. Applying conditional data resolution based on the time frame so not to exceed the callback size should solve this.
