### ISSUE TITLE
[ Modal ] - Slow loading speed when loading entities with large number of ASNs

### ISSUE THREAD

**Issue by JayWebz** [CAIDA/ioda-ui#211]
Loading raw signals for an entity in the Horizon time series with large number of related entities takes a very long time. Look into speed. US as example.

**Comment by JayWebz** [comment]
Relates to https://github.com/CAIDA/ioda-api/issues/52

**Comment by digizeph** [comment]
@JayWebz can you provide some details on the queries being slow here? Are these for querying for raw signals or summaries? What queries do you send from the front-end side?

**Comment by JayWebz** [comment]
@digizeph This was referring to being timed out when loading the US asn raw signal table I believe. This is no longer happening though as the api call for https://api.ioda.caida.org/dev/entities/asn/?relatedTo=country/US. This is resolving itself in ~20-25 seconds each time though, which seems very reasonable. Going to close this ticket.
