### ISSUE TITLE
User should be able to create a URL that points to the currently selected time frame even if the time frame was selected as a relative range (e.g., last 24hrs).

### ISSUE THREAD

**Issue by albertodainotti** [CAIDA/ioda-ui#315]
In v1, we would copy the string of the time range at the right bottom of the graph and paste it in the date picker and it would reload the page, adding that time range to the URL

**Comment by JayWebz** [comment]
Observed Criteria from v1
- The input updates after each keystroke
- If an invalid range is set (be it from erasing a character to put a new one), the page loads an error message in it's own panel in the UI.
- user can input a relative range like _-24h - now_, the hyphen is used to determine the start/end date.

**Comment by JayWebz** [comment]
Dashboard page still needs some fixing

**Comment by JayWebz** [comment]
Resolved in https://github.com/CAIDA/ioda-ui/pull/325
