### ISSUE TITLE
[ XY Plot Time Series ] - N.A. value jumps to 100%

### ISSUE THREAD

**Issue by albertodainotti** [CAIDA/ioda-ui#318]
IBR data (in influxDB, not dbats so it's different in ioda v1) stops on July 4th:
https://explore.ioda.caida.org/d/dk7Y9d9Mk/ioda-explorer?orgId=1  [soon this graph will change 'cause we'll switch to another influxdb bucket but trust me that the data is N.A. starting around July 4th]

But v2's xygraph shows it topping to 100%:
https://dev.v2.ioda.caida.org/country/IT?from=1625122800&until=1625727600

**Comment by JayWebz** [comment]
Found a similar instance with BGP being down, but normalized values populate at 100. https://dev.v2.ioda.caida.org/country/TD?from=1625673097&until=1625759497

**Comment by JayWebz** [comment]
localhost url - http://localhost:8000/country/IT?from=1622793120&until=1622905860
