### ISSUE TITLE
[ Horizon Time Series ] - Cap ASes on raw signal horizon time series view to 10-20 sorted by score. Load more as requested

### ISSUE THREAD

**Issue by JayWebz** [CAIDA/ioda-ui#82]

**Comment by JayWebz** [comment]
@digizeph - could you look into adding a `limit` and `page` property to the signal endpoints?
/dev/signals/raw/{entityType}/{entityCode}
/dev/signals/events/{entityType}/{entityCode}

Then I can control the number to load like I do with the summary table.

**Comment by digizeph** [comment]
I'll investigate it this week.

**Comment by digizeph** [comment]
We decided the API extension is no longer necessary. The pagination of signals can be done at client side.

**Comment by JayWebz** [comment]
The cap can possibly be removed or increased once https://github.com/CAIDA/ioda-api/issues/44 is resolved.

**Comment by JayWebz** [comment]
loading 10 at a time seems to work okay, and allows for me to reuse table logic code easier. Going to set that as the standard amount displayed for this reason. Is it preferred to load an additional 10 at a time or load a new set of 10 every time? Currently I have it set to swap out for a new set of 10 every time instead of adding on so that the functionality also matches the table. If tacking them on is preferred, that is easy enough to switch.

**Comment by digizeph** [comment]
I think your current method's description makes sense. Just to confirm, when you go back one page, you won't need to make additional calls, correct?

**Comment by JayWebz** [comment]
I am currently not storing prior data at this time. I'm not sure if there is a point where storing that amount of data after a couple clicks through adding additional data will be too large to handle, more of a concern that can be tested out. Right now, an api call to load a next/prior set of 10 is about 14-25s.

**Comment by JayWebz** [comment]
sorry, scratch that. I was thinking about slicing from it further along in the process, but it seems alright with the concept of going back one page and no new api call is made. Making that update now.

**Comment by JayWebz** [comment]
@digizeph I reverted the master branch to no longer have the horizon time series pagination for raw signals and removed the cap for both the modal windows. Reassigning to you.

**Comment by JayWebz** [comment]
Api sped up and released to dev. Closing issue.
